In [1]:
from collections import Counter, defaultdict
from datetime import datetime
from pathlib import Path
import math
import time

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [18]:
PATH = "../data/TreatedData/TreatedData.csv"
SAVE_PATH = "../data/TreatedData/TreatedData.csv"

KeyboardInterrupt:

In [30]:
labels = dataset.iloc[:,0]
dataset_no_lables = dataset.iloc[:, 1:]

In [31]:
dataset_no_lables.head()

,X_0,Y_0,Z_0,X_1,Y_1,Z_1,X_2,Y_2,Z_2,X_3,...,Z_464,X_465,Y_465,Z_465,X_466,Y_466,Z_466,X_467,Y_467,Z_467
0,0.496172,0.444780,-0.030373,0.491899,0.421330,-0.058224,0.494451,0.428108,-0.030852,0.482987,...,0.000898,0.511758,0.385753,-0.007160,0.571504,0.380450,0.011499,0.576769,0.379315,0.011428
1,0.495403,0.445214,-0.030503,0.491604,0.421221,-0.057968,0.494133,0.428579,-0.030973,0.482722,...,0.000560,0.512008,0.385401,-0.007159,0.571704,0.379690,0.009500,0.577298,0.378401,0.009368
2,0.496242,0.445045,-0.029657,0.492032,0.421750,-0.057864,0.494796,0.428696,-0.030954,0.483319,...,0.000214,0.512516,0.386302,-0.007647,0.571996,0.381308,0.009131,0.577683,0.379969,0.009014
3,0.497706,0.444049,-0.030082,0.494919,0.420446,-0.056945,0.496879,0.427491,-0.030656,0.486426,...,0.000730,0.514800,0.387282,-0.006981,0.573056,0.383648,0.009844,0.578896,0.381756,0.009843
4,0.497005,0.442463,-0.029723,0.494933,0.421154,-0.056429,0.496664,0.427733,-0.030633,0.487015,...,0.001288,0.515992,0.386963,-0.006404,0.574032,0.384067,0.010379,0.579975,0.382123,0.010510

In [16]:

# =========================================================
# PARTE 1: NOMEANDO AS COLUNAS (Base que você enviou)
# =========================================================
nomes_colunas = []
num_pontos = 468

for i in range(num_pontos):
    nomes_colunas.append(f'X_{i}')
    nomes_colunas.append(f'Y_{i}')
    nomes_colunas.append(f'Z_{i}')

novo_dataset = dataset_no_lables.copy()
novo_dataset.columns = nomes_colunas

In [17]:
novo_dataset.head()

,X_0,Y_0,Z_0,X_1,Y_1,Z_1,X_2,Y_2,Z_2,X_3,...,Z_464,X_465,Y_465,Z_465,X_466,Y_466,Z_466,X_467,Y_467,Z_467
0,0.496172,0.444780,-0.030373,0.491899,0.421330,-0.058224,0.494451,0.428108,-0.030852,0.482987,...,0.000898,0.511758,0.385753,-0.007160,0.571504,0.380450,0.011499,0.576769,0.379315,0.011428
1,0.495403,0.445214,-0.030503,0.491604,0.421221,-0.057968,0.494133,0.428579,-0.030973,0.482722,...,0.000560,0.512008,0.385401,-0.007159,0.571704,0.379690,0.009500,0.577298,0.378401,0.009368
2,0.496242,0.445045,-0.029657,0.492032,0.421750,-0.057864,0.494796,0.428696,-0.030954,0.483319,...,0.000214,0.512516,0.386302,-0.007647,0.571996,0.381308,0.009131,0.577683,0.379969,0.009014
3,0.497706,0.444049,-0.030082,0.494919,0.420446,-0.056945,0.496879,0.427491,-0.030656,0.486426,...,0.000730,0.514800,0.387282,-0.006981,0.573056,0.383648,0.009844,0.578896,0.381756,0.009843
4,0.497005,0.442463,-0.029723,0.494933,0.421154,-0.056429,0.496664,0.427733,-0.030633,0.487015,...,0.001288,0.515992,0.386963,-0.006404,0.574032,0.384067,0.010379,0.579975,0.382123,0.010510

In [ ]:
labels.value_counts(normalize=True)

0
12    12.004771
8     11.755577
2     10.963211
5     10.276375
4      7.549429
9      7.487795
3      6.846187
6      6.768147
7      6.758393
11     6.238721
1      4.460663
10     4.458003
0      4.432729
Name: proportion, dtype: float64

In [19]:
def change_label(value):
    possible_values = [3,4]
    if value not in possible_values:
        return -1
    else:
        return value


labels = labels.transform(change_label)

In [22]:
transformed_dataset = pd.concat([labels, novo_dataset],axis=1)

In [23]:
transformed_dataset.head()

,0,X_0,Y_0,Z_0,X_1,Y_1,Z_1,X_2,Y_2,Z_2,...,Z_464,X_465,Y_465,Z_465,X_466,Y_466,Z_466,X_467,Y_467,Z_467
0,-1,0.496172,0.444780,-0.030373,0.491899,0.421330,-0.058224,0.494451,0.428108,-0.030852,...,0.000898,0.511758,0.385753,-0.007160,0.571504,0.380450,0.011499,0.576769,0.379315,0.011428
1,-1,0.495403,0.445214,-0.030503,0.491604,0.421221,-0.057968,0.494133,0.428579,-0.030973,...,0.000560,0.512008,0.385401,-0.007159,0.571704,0.379690,0.009500,0.577298,0.378401,0.009368
2,-1,0.496242,0.445045,-0.029657,0.492032,0.421750,-0.057864,0.494796,0.428696,-0.030954,...,0.000214,0.512516,0.386302,-0.007647,0.571996,0.381308,0.009131,0.577683,0.379969,0.009014
3,-1,0.497706,0.444049,-0.030082,0.494919,0.420446,-0.056945,0.496879,0.427491,-0.030656,...,0.000730,0.514800,0.387282,-0.006981,0.573056,0.383648,0.009844,0.578896,0.381756,0.009843
4,-1,0.497005,0.442463,-0.029723,0.494933,0.421154,-0.056429,0.496664,0.427733,-0.030633,...,0.001288,0.515992,0.386963,-0.006404,0.574032,0.384067,0.010379,0.579975,0.382123,0.010510

In [ ]:
'weights' '-> Balanced'

In [26]:
import os

# Pega apenas o caminho da pasta (ignorando o nome do arquivo no final)
# Vai retornar: '../data/TreatedData'
save_dir = os.path.dirname(SAVE_PATH)

# Se a pasta existir no caminho e ainda não estiver criada, ele cria apenas a pasta
if save_dir and not os.path.exists(save_dir):
    os.makedirs(save_dir)

# Agora sim ele salva o arquivo de texto (.csv) dentro da pasta correta
transformed_dataset.to_csv(SAVE_PATH, index=False)

In [3]:
dataset_original = pd.read_csv("../data/archive/FaceGest_landmarks.csv")

In [2]:
dataset = pd.read_csv("../data/TreatedData/TreatedData.csv")

In [11]:
dataset = dataset[dataset["0"] != -1]

In [19]:
dataset.to_csv(SAVE_PATH)